"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['human_play.py']
APP_NAME = "Gomoku Zero"
DATA_FILES = ['best_policy.model']
OPTIONS = {'iconfile': 'app.icns'}

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
